import pygame

if not pygame.get_init():
    pygame.display.init()


#Graphic
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
FPS = 60


#Main menu
BUTTON_START_WIDTH = 150
BUTTON_START_HEIGHT = 75
BUTTON_START_X = (WINDOW_WIDTH/2) - (BUTTON_START_WIDTH/2)
BUTTON_START_Y = (WINDOW_HEIGHT/2) - (BUTTON_START_HEIGHT/2)

#Main scene
BUTTON_HOUSE_WIDTH = 150
BUTTON_HOUSE_HEIGHT = 150
BUTTON_HOUSE_X = 1000
BUTTON_HOUSE_Y = 20

HOUSE_UNLOCKED = True

BUTTON_MURKEY_WATER_WIDTH = 250
BUTTON_MURKEY_WATER_HEIGHT = 200
BUTTON_MURKEY_WATER_X = 200
BUTTON_MURKEY_WATER_Y = 400

MURKEY_WATER_UNLOCKED = True
MURKEY_WATER_IMAGE_PATH = "assets/murkey_water.png"

BUTTON_BOAT_HOUSE_WIDTH = 150
BUTTON_BOAT_HOUSE_HEIGHT = 125
BUTTON_BOAT_HOUSE_X = 750
BUTTON_BOAT_HOUSE_Y = 200

BOAT_HOUSE_UNLOCKED = False
BOAT_HOUSE_IMAGE_PATH = "assets/boat_house.png"

BUTTON_CHAPEL_WIDTH = 100
BUTTON_CHAPEL_HEIGHT = 120
BUTTON_CHAPEL_X = 300
BUTTON_CHAPEL_Y = 200

CHAPEL_UNLOCKED = False

BUTTON_LIGHTHOUSE_WIDTH = 100
BUTTON_LIGHTHOUSE_HEIGHT = 100
BUTTON_LIGHTHOUSE_X = 1100
BUTTON_LIGHTHOUSE_Y = 500

LIGHTHOUSE_UNLOCKED = False
LIGHTHOUSE_IMAGE_PATH = "assets/light_house.png"