import pygame

if not pygame.get_init():
    pygame.display.init()


#Graphic
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
FPS = 60


#Main menu
BUTTON_START_WIDTH = 150
BUTTON_START_HEIGHT = 75
BUTTON_START_X = (WINDOW_WIDTH/2) - (BUTTON_START_WIDTH/2)
BUTTON_START_Y = (WINDOW_HEIGHT/2) - (BUTTON_START_HEIGHT/2)

#Main scene
BUTTON_HOUSE_WIDTH = 150
BUTTON_HOUSE_HEIGHT = 150
BUTTON_HOUSE_X = 1000
BUTTON_HOUSE_Y = 20

HOUSE_UNLOCKED = True
HOUSE_IMAGE_PATH = "assets/house.png"

BUTTON_MURKEY_WATER_WIDTH = 250
BUTTON_MURKEY_WATER_HEIGHT = 200
BUTTON_MURKEY_WATER_X = 200
BUTTON_MURKEY_WATER_Y = 400

MURKEY_WATER_UNLOCKED = True
MURKEY_WATER_IMAGE_PATH = "assets/murkey_water.png"

BUTTON_BOAT_HOUSE_WIDTH = 150
BUTTON_BOAT_HOUSE_HEIGHT = 125
BUTTON_BOAT_HOUSE_X = 750
BUTTON_BOAT_HOUSE_Y = 200

BOAT_HOUSE_UNLOCKED = False
BOAT_HOUSE_IMAGE_PATH = "assets/boat_house.png"

BUTTON_CHAPEL_WIDTH = 100
BUTTON_CHAPEL_HEIGHT = 120
BUTTON_CHAPEL_X = 300
BUTTON_CHAPEL_Y = 200

CHAPEL_UNLOCKED = False
CHAPEL_IMAGE_PATH = "assets/chapel.png"

BUTTON_LIGHTHOUSE_WIDTH = 100
BUTTON_LIGHTHOUSE_HEIGHT = 100
BUTTON_LIGHTHOUSE_X = 1100
BUTTON_LIGHTHOUSE_Y = 500

LIGHTHOUSE_UNLOCKED = False
LIGHTHOUSE_IMAGE_PATH = "assets/light_house.png"

BUTTON_OLD_CHAPEL_WIDTH = 130
BUTTON_OLD_CHAPEL_HEIGHT = 130
BUTTON_OLD_CHAPEL_X = 60
BUTTON_OLD_CHAPEL_Y = 20

OLD_CHAPEL_UNLOCKED = True
OLD_CHAPEL_IMAGE_PATH = "assets/chapel.png"

BACKGROUND_IMAGE_PATH = "assets/scene_main_background.png"

#Combat
BUTTON_INPUT_BOX_WIDTH = 700
BUTTON_INPUT_BOX_HEIGHT = 40
BUTTON_INPUT_BOX_X = (WINDOW_WIDTH/2) - (BUTTON_INPUT_BOX_WIDTH/2)
BUTTON_INPUT_BOX_Y = WINDOW_HEIGHT - BUTTON_INPUT_BOX_HEIGHT - 20

BUTTON_ENEMY_TEXT_BOX_WIDTH = 700
BUTTON_ENEMY_TEXT_BOX_HEIGHT = 40
BUTTON_ENEMY_TEXT_BOX_X = (WINDOW_WIDTH/2) - (BUTTON_ENEMY_TEXT_BOX_WIDTH/2)
BUTTON_ENEMY_TEXT_BOX_Y = 20

IMAGE_ENEMY_PATH = ""
IMAGE_ENEMY_X = 0
IMAGE_ENEMY_Y = 0

BUFFER_TIME = 3

#Prompt timers per area
TIME_PER_PROMPT_HOUSE = 12
TIME_PER_PROMPT_MURKEY_WATER = 8
TIME_PER_PROMPT_BOAT_HOUSE = 12
TIME_PER_PROMPT_CHAPEL = 12
TIME_PER_PROMPT_OLD_CHAPEL = 12
TIME_PER_PROMPT_LIGHTHOUSE = 27

#Wrong letter damage per area
DAMAGE_WRONG_LETTER_HOUSE = 30
DAMAGE_WRONG_LETTER_MURKEY_WATER = 30
DAMAGE_WRONG_LETTER_BOAT_HOUSE = 30
DAMAGE_WRONG_LETTER_CHAPEL = 30
DAMAGE_WRONG_LETTER_OLD_CHAPEL = 30
DAMAGE_WRONG_LETTER_LIGHTHOUSE = 15

#Damage flash
DAMAGE_FLASH_DURATION = 0.3
DAMAGE_PAUSE_DURATION = 2.0

#Player Stamina bar
PLAYER_STAMINA_BAR_X = WINDOW_WIDTH - 75
PLAYER_STAMINA_BAR_Y = 100
PLAYER_STAMINA_BAR_W = 25
PLAYER_STAMINA_BAR_H = 520

#Player HP bar
PLAYER_HP_BAR_X = 50
PLAYER_HP_BAR_Y = 100
PLAYER_HP_BAR_W = 25
PLAYER_HP_BAR_H = 520

#Skills
SKILL_CONTEMPLATION_COST = 20
SKILL_CONTEMPLATION_DURATION = 4.0

SKILL_DELIRIUM_COST = 25
SKILL_DELIRIUM_DURATION = 20.0

SKILL_CONCENTRATION_COST = 15
SKILL_CONCENTRATION_TIME_BONUS = 5.0

SKILL_DENIAL_COST = 30

SKILL_ACCEPTANCE_COST = 20
SKILL_ACCEPTANCE_DURATION = 15.0

#Timer bar
TIMER_BAR_X = BUTTON_INPUT_BOX_X
TIMER_BAR_Y = BUTTON_INPUT_BOX_Y - 20
TIMER_BAR_W = BUTTON_INPUT_BOX_WIDTH
TIMER_BAR_H = 12

#Skill slots
SKILL_SLOT_COUNT = 5
SKILL_SLOT_SIZE = 80
SKILL_SLOT_Y = TIMER_BAR_Y - 10 - SKILL_SLOT_SIZE

#Player base stats
PLAYER_BASE_HP = 100
PLAYER_BASE_STAMINA = 100
PLAYER_BASE_STAMINA_REGEN = 2.0

#Persistent inventory (mutated in-place across scenes)
player_inventory = []
player_equipment = {"head": None, "body": None, "legs": None, "weapon": None}

#Inventory button on main map
BUTTON_INVENTORY_WIDTH = 120
BUTTON_INVENTORY_HEIGHT = 40
BUTTON_INVENTORY_X = WINDOW_WIDTH - 130
BUTTON_INVENTORY_Y = WINDOW_HEIGHT - 50